# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "centralized-infra"
    key                  = "AKSClustersInfra/role-definition-nonprod/terraform.tfstate"
    resource_group_name  = "Al-Resource-Group-Common"
    storage_account_name = "arrivelogisticsterraform"
  }
}
