trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md
    - .gitignore
    - pull-request-pipeline.yml

resources:
  repositories:
  - repository: templates
    type: git
    name: Accelerate/pipeline-templates

pool:
  vmImage: "ubuntu-latest"

variables:
  sshFile: 'az_key'
  knownHostsEntry: 'vs-ssh.visualstudio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H'

stages:
- stage: "dev"
  jobs:
  - template: terraform-apply-manual-approve.yaml@templates
    parameters:
      env: dev
      sshFile: $(sshFile)
      knownHostsEntry: $(knownHostsEntry)
- stage: "test"
  jobs:
  - template: terraform-apply-manual-approve.yaml@templates
    parameters:
      env: test
      sshFile: $(sshFile)
      knownHostsEntry: $(knownHostsEntry)
- stage: "stg"
  jobs:
  - template: terraform-apply-manual-approve.yaml@templates
    parameters:
      env: stg
      sshFile: $(sshFile)
      knownHostsEntry: $(knownHostsEntry)
- stage: "prod"
  jobs:
  - template: terraform-apply-manual-approve.yaml@templates
    parameters:
      env: prod
      sshFile: $(sshFile)
      knownHostsEntry: $(knownHostsEntry)